#include "db/PlacementDB.h"
#include "density/ExactBinGrid.h"
#include "density/ExactDensityEvaluator.h"
#include "evaluator/HPWLEvaluator.h"
#include "parser/LimboBookshelfAdapter.h"
#include <cstdlib>
#include <iomanip>
#include <iostream>
#include <map>
#include <stdexcept>
#include <string>

namespace { struct Options{std::string aux; int bins_x=64; int bins_y=64; double target_density=0.9;}; void usage(const char* a){std::cerr<<"Usage: "<<a<<" --aux <benchmark.aux> [--bins <nx> <ny>] [--target-density <value>]\n";} Options parse(int argc,char**argv){Options o; for(int i=1;i<argc;++i){std::string s=argv[i]; if(s=="--aux"&&i+1<argc)o.aux=argv[++i]; else if(s=="--bins"&&i+2<argc){o.bins_x=std::stoi(argv[++i]); o.bins_y=std::stoi(argv[++i]);} else if(s=="--target-density"&&i+1<argc)o.target_density=std::stod(argv[++i]); else if(s=="-h"||s=="--help"){usage(argv[0]); std::exit(0);} else throw std::invalid_argument("unknown or incomplete argument: "+s);} if(o.aux.empty()) throw std::invalid_argument("missing --aux"); return o;} }

int main(int argc,char**argv){ try{ const Options opt=parse(argc,argv); PlacementDB db; LimboBookshelfAdapter adapter(db); if(!adapter.read(opt.aux)) throw std::runtime_error("failed to read Bookshelf benchmark"); size_t movable=0,fixed=0; std::map<std::string,size_t> orient; for(const auto& c: db.cells()){ if(c.isMovable()) ++movable; else ++fixed; ++orient[c.orientation]; } const Box core=db.coreBounds(); HPWLEvaluator hpwl; const double input_hpwl=hpwl.totalHPWL(db); std::cout<<std::fixed<<std::setprecision(6); std::cout<<"[Database]\n"<<"cells "<<db.cells().size()<<"\n"<<"movable_cells "<<movable<<"\n"<<"fixed_cells "<<fixed<<"\n"<<"nets "<<db.nets().size()<<"\n"<<"pins "<<db.pins().size()<<"\n"<<"rows "<<db.rows().size()<<"\n"<<"core_bounds "<<core.lx<<" "<<core.ly<<" "<<core.ux<<" "<<core.uy<<"\n\n"; std::cout<<"[Input Placement]\ninput_hpwl "<<input_hpwl<<"\n\n"; std::cout<<"[Orientation Statistics]\n"; bool non_n=false; for(const auto& kv: orient){std::cout<<kv.first<<" "<<kv.second<<"\n"; if(kv.first!="N") non_n=true;} if(non_n) std::cerr<<"Warning: non-N orientations exist; pin offsets are still interpreted with N-orientation semantics and coordinates are unchanged.\n"; ExactBinGrid grid(db,opt.bins_x,opt.bins_y,opt.target_density); ExactDensityMetrics m=ExactDensityEvaluator().evaluate(grid); std::cout<<"\n[Exact Density]\n"<<"bins_x "<<grid.numBinsX()<<"\n"<<"bins_y "<<grid.numBinsY()<<"\n"<<"bin_width "<<grid.binWidth()<<"\n"<<"bin_height "<<grid.binHeight()<<"\n"<<"target_density "<<grid.targetDensity()<<"\n"<<"total_cell_area "<<m.total_cell_area<<"\n"<<"total_movable_area "<<m.total_movable_area<<"\n"<<"total_fixed_area "<<m.total_fixed_area<<"\n"<<"total_overflow "<<m.total_overflow<<"\n"<<"overflow_ratio "<<m.overflow_ratio<<"\n"<<"overflow_bin_count "<<m.overflow_bin_count<<"\n"<<"maximum_bin_density "<<m.maximum_bin_density<<"\n"; return 0; } catch(const std::exception& e){ std::cerr<<"Error: "<<e.what()<<"\n"; usage(argv[0]); return 1; } }
