#include "db/PlacementDB.h"
#include "grid/BinGrid.h"
#include "evaluator/ObjectiveEvaluator.h"
#include "optimizer/GlobalPlacer.h"
#include <cassert>
#include <cmath>
#include <limits>
#include <stdexcept>

namespace { constexpr double EPS=1e-8; void row(PlacementDB& db,double ux=100,double uy=20){Row r; r.x_start=0; r.x_end=ux; r.y=0; r.height=uy; r.site_width=1; r.site_spacing=1; r.num_sites=(int)ux; db.addRow(r);} int cell(PlacementDB& db,const char*n,double x,double y,double w=2,double h=2,bool fixed=false){int id=db.addCell(n,w,h,CellType::Standard); db.setCellLocation(n,x,y,fixed); return id;} void net(PlacementDB& db,int a,int b){int n=db.addNet("n"+std::to_string(db.nets().size())); db.addPin(a,n,0,0,"B"); db.addPin(b,n,0,0,"B");} GlobalPlacerConfig cfg(){GlobalPlacerConfig c; c.bins_x=4;c.bins_y=1;c.max_iterations=8;c.report_interval=100;c.relative_improvement_tolerance=0;c.initial_step_fraction=.5;c.max_line_search_trials=6;return c;} }
int main(){
 {PlacementDB d1,d2; row(d1); row(d2); int a1=cell(d1,"a",0,0),b1=cell(d1,"b",80,0); int a2=cell(d2,"a",0,0),b2=cell(d2,"b",80,0); net(d1,a1,b1); net(d2,a2,b2); auto c1=cfg(), c2=cfg(); c1.density_weight=0; c2.density_weight=0; c2.method=GlobalPlacementMethod::DirectSubgradient; auto r1=GlobalPlacer(c1).optimize(d1), r2=GlobalPlacer(c2).optimize(d2); assert(std::abs(r1.final_metrics.total_cost-r2.final_metrics.total_cost)<EPS);}
 {PlacementDB db; row(db); int a=cell(db,"a",0,0),b=cell(db,"b",80,0); net(db,a,b); auto c=cfg(); c.method=GlobalPlacementMethod::MoreauProximal; c.density_weight=0; c.moreau.max_inner_iterations=5; c.moreau.relative_improvement_tolerance=0; auto r=GlobalPlacer(c).optimize(db); assert(r.final_metrics.total_cost<=r.initial_metrics.total_cost+EPS); assert(r.accepted_iterations>0); bool saw=false; for(auto& h:r.history) saw|=h.used_moreau&&h.accepted; assert(saw);}
 {PlacementDB db; row(db); int f=cell(db,"f",10,0,2,2,true), m=cell(db,"m",0,0); net(db,f,m); auto x=db.cell(f).x,y=db.cell(f).y; auto c=cfg(); c.method=GlobalPlacementMethod::MoreauProximal; c.density_weight=0; auto r=GlobalPlacer(c).optimize(db); (void)r; assert(db.cell(f).x==x&&db.cell(f).y==y);}
 {PlacementDB d1,d2; row(d1); row(d2); int a1=cell(d1,"a",0,0),b1=cell(d1,"b",80,0); int a2=cell(d2,"a",0,0),b2=cell(d2,"b",80,0); net(d1,a1,b1); net(d2,a2,b2); auto c=cfg(); c.method=GlobalPlacementMethod::MoreauProximal; c.density_weight=0; auto r1=GlobalPlacer(c).optimize(d1), r2=GlobalPlacer(c).optimize(d2); assert(std::abs(r1.final_metrics.total_cost-r2.final_metrics.total_cost)<EPS); for(size_t i=0;i<d1.cells().size();++i) assert(std::abs(d1.cells()[i].x-d2.cells()[i].x)<EPS);}
 {PlacementDB db; row(db); int a=cell(db,"a",0,0),b=cell(db,"b",80,0); net(db,a,b); auto c=cfg(); c.method=GlobalPlacementMethod::MoreauProximal; c.density_weight=0; c.moreau.initial_step_fraction=100; c.moreau.max_line_search_trials=1; c.moreau.max_stall_iterations=1; c.max_stall_iterations=1; auto r=GlobalPlacer(c).optimize(db); assert(r.final_metrics.total_cost<=r.initial_metrics.total_cost+EPS);}
 {PlacementDB d1,d2; row(d1); row(d2); int a1=cell(d1,"a",0,0),b1=cell(d1,"b",80,0); int a2=cell(d2,"a",0,0),b2=cell(d2,"b",80,0); net(d1,a1,b1); net(d2,a2,b2); auto cd=cfg(); cd.density_weight=0; auto cm=cd; cm.method=GlobalPlacementMethod::MoreauProximal; auto rd=GlobalPlacer(cd).optimize(d1), rm=GlobalPlacer(cm).optimize(d2); assert(std::isfinite(rd.final_metrics.total_cost)&&std::isfinite(rm.final_metrics.total_cost));}

 {PlacementDB db; row(db); int a=cell(db,"a",0,0), b=cell(db,"b",80,0); net(db,a,b); auto c=cfg(); c.density_weight=0; auto r=GlobalPlacer(c).optimize(db); assert(r.final_metrics.total_cost<=r.initial_metrics.total_cost+EPS); assert(r.final_metrics.hpwl<=r.initial_metrics.hpwl+EPS); assert(r.accepted_iterations>0); for(auto& ce:db.cells()) assert(std::isfinite(ce.x)&&std::isfinite(ce.y));}
 {PlacementDB db; row(db); int f=cell(db,"f",10,3,3,3,true); cell(db,"m",0,0); auto c=cfg(); auto x=db.cell(f).x,y=db.cell(f).y; (void)GlobalPlacer(c).optimize(db); assert(db.cell(f).x==x&&db.cell(f).y==y&&db.cell(f).is_fixed);} 
 {PlacementDB db; row(db,40,10); cell(db,"a",0,0,8,10); cell(db,"b",0,0,8,10); BinGrid g(db,2,1,0.5); auto init=ObjectiveEvaluator{}.evaluate(db,g,1); assert(init.density_penalty>0); auto c=cfg(); c.bins_x=2;c.bins_y=1;c.density_weight=1;c.max_iterations=10;c.initial_step_fraction=.25; auto r=GlobalPlacer(c).optimize(db); assert(r.final_metrics.density_penalty<=init.density_penalty+EPS); assert(r.final_metrics.total_overflow<=init.total_overflow+EPS);} 
 {PlacementDB db; row(db,20,20); int a=cell(db,"a",18,18); int b=cell(db,"b",1,1); net(db,a,b); auto c=cfg(); c.bins_x=2;c.bins_y=2;c.density_weight=0;c.initial_step_fraction=10;c.max_iterations=2; (void)GlobalPlacer(c).optimize(db); Box core=db.coreBounds(); for(auto& ce:db.cells()) if(ce.isMovable()) assert(ce.x>=core.lx-EPS&&ce.y>=core.ly-EPS&&ce.x+ce.width<=core.ux+EPS&&ce.y+ce.height<=core.uy+EPS);} 
 {PlacementDB db; row(db); int a=cell(db,"a",1,1); auto c=cfg(); c.max_iterations=0; auto x=db.cell(a).x,y=db.cell(a).y; auto r=GlobalPlacer(c).optimize(db); assert(db.cell(a).x==x&&db.cell(a).y==y); assert(r.history.empty()); assert(std::abs(r.initial_metrics.total_cost-r.final_metrics.total_cost)<EPS);} 
 {PlacementDB d1,d2; row(d1); row(d2); int a1=cell(d1,"a",0,0),b1=cell(d1,"b",0,0); int a2=cell(d2,"a",0,0),b2=cell(d2,"b",0,0); net(d1,a1,b1); net(d2,a2,b2); auto c=cfg(); auto r1=GlobalPlacer(c).optimize(d1), r2=GlobalPlacer(c).optimize(d2); assert(std::abs(r1.final_metrics.total_cost-r2.final_metrics.total_cost)<EPS); assert(r1.history.size()==r2.history.size()); for(size_t i=0;i<r1.history.size();++i) assert(r1.history[i].accepted==r2.history[i].accepted); for(size_t i=0;i<d1.cells().size();++i){assert(std::abs(d1.cells()[i].x-d2.cells()[i].x)<EPS); assert(std::abs(d1.cells()[i].y-d2.cells()[i].y)<EPS);}}
 {auto c=cfg(); c.bins_x=0; bool th=false; try{GlobalPlacer p(c);}catch(const std::invalid_argument&){th=true;} assert(th); c=cfg(); c.density_weight=-1; th=false; try{GlobalPlacer p(c);}catch(const std::invalid_argument&){th=true;} assert(th);} 
 {PlacementDB db; row(db); int a=cell(db,"a",0,0), b=cell(db,"b",80,0); net(db,a,b); auto c=cfg(); c.density_weight=0; c.initial_step_fraction=100; c.max_line_search_trials=1; c.max_iterations=2; auto r=GlobalPlacer(c).optimize(db); assert(r.final_metrics.total_cost<=r.best_metrics.total_cost+EPS); assert(r.final_metrics.total_cost<=r.initial_metrics.total_cost+EPS);} 
}
