#include "optimizer/MoreauProximalSolver.h"
#include "evaluator/ObjectiveEvaluator.h"
#include "grid/BinGrid.h"
#include "db/PlacementDB.h"
#include <cassert>
#include <cmath>
#include <limits>
#include <stdexcept>
#include <vector>
namespace{constexpr double EPS=1e-8; void near(double a,double b,double e=EPS){assert(std::abs(a-b)<=e);} void row(PlacementDB& db,double w=100,double h=20){Row r; r.x_start=0;r.x_end=w;r.y=0;r.height=h;r.site_width=1;r.site_spacing=1;r.num_sites=(int)w;db.addRow(r);} int cell(PlacementDB& db,const char*n,double x,double y,double w=2,double h=2,bool fixed=false){int id=db.addCell(n,w,h,CellType::Standard);db.setCellLocation(n,x,y,fixed);return id;} void net(PlacementDB& db,int a,int b){int n=db.addNet("n"+std::to_string(db.nets().size()));db.addPin(a,n,0,0,"B");db.addPin(b,n,0,0,"B");} PlacementDB two(){PlacementDB db;row(db);int a=cell(db,"a",0,0),b=cell(db,"b",80,0);net(db,a,b);return db;} MoreauProximalConfig cfg(){MoreauProximalConfig c;c.max_inner_iterations=5;c.relative_improvement_tolerance=0;c.initial_step_fraction=.2;c.max_line_search_trials=8;return c;} double dist(const PlacementDB&db){return std::hypot(db.cell(0).x-db.cell(1).x,db.cell(0).y-db.cell(1).y);} }
int main(){
 {auto db=two();BinGrid g(db,4,1,1);SubgradientConfig sc;sc.density_weight=0;MoreauProximalConfig c=cfg();c.max_inner_iterations=0;auto r=MoreauProximalSolver(c,sc).solve(db,g);near(r.anchor_proximal_metrics.squared_displacement,0);near(r.anchor_proximal_metrics.proximal_term,0);near(r.anchor_proximal_metrics.proximal_objective,r.anchor_metrics.total_cost);assert(!r.accepted&&r.history.empty());}
 {auto db=two();BinGrid g(db,4,1,1);SubgradientConfig sc;sc.density_weight=0;auto c=cfg();auto r=MoreauProximalSolver(c,sc).solve(db,g);assert(r.accepted);assert(r.final_proximal_metrics.proximal_objective<r.anchor_proximal_metrics.proximal_objective);assert(r.final_metrics.total_cost<=r.anchor_metrics.total_cost+EPS);assert(dist(db)<80);for(auto& ce:db.cells())assert(std::isfinite(ce.x)&&std::isfinite(ce.y));assert(r.final_proximal_metrics.squared_displacement>0&&r.final_proximal_metrics.proximal_term>0);double L=std::hypot(g.coreBounds().width(),g.coreBounds().height());near(r.final_proximal_metrics.proximal_term,r.final_proximal_metrics.squared_displacement/(2*c.mu*L*L));}
 {PlacementDB db;row(db);int f=cell(db,"f",50,0,2,2,true),m=cell(db,"m",0,0);net(db,f,m);double x=db.cell(f).x,y=db.cell(f).y;bool isf=db.cell(f).is_fixed;BinGrid g(db,4,1,1);SubgradientConfig sc;sc.density_weight=0;auto r=MoreauProximalSolver(cfg(),sc).solve(db,g);(void)r;assert(db.cell(f).x==x&&db.cell(f).y==y&&db.cell(f).is_fixed==isf);}
 {auto d1=two(),d2=two();BinGrid g1(d1,4,1,1),g2(d2,4,1,1);SubgradientConfig sc;sc.density_weight=0;auto c1=cfg(),c2=cfg();c1.mu=.01;c2.mu=10;auto r1=MoreauProximalSolver(c1,sc).solve(d1,g1);auto r2=MoreauProximalSolver(c2,sc).solve(d2,g2);assert(r1.final_proximal_metrics.displacement_rms<=r2.final_proximal_metrics.displacement_rms+EPS);}
 {PlacementDB db;row(db);cell(db,"a",0,0,1,1);BinGrid g(db,4,1,1);auto c=cfg();SubgradientConfig sc;sc.density_weight=0;auto before=db.cell(0).x;auto r=MoreauProximalSolver(c,sc).solve(db,g);near(db.cell(0).x,before);assert(!r.accepted);assert(r.termination_reason.find("residual")!=std::string::npos||r.termination_reason.find("improvement")!=std::string::npos);}
 {auto db=two();BinGrid g(db,4,1,1);auto c=cfg();c.initial_step_fraction=100;c.max_line_search_trials=1;c.max_stall_iterations=1;SubgradientConfig sc;sc.density_weight=0;auto r=MoreauProximalSolver(c,sc).solve(db,g);if(!r.accepted){near(db.cell(0).x,0);near(db.cell(1).x,80);} }
 {PlacementDB db;row(db,20,20);int a=cell(db,"a",18,18),b=cell(db,"b",0,0);net(db,a,b);BinGrid g(db,2,2,1);SubgradientConfig sc;sc.density_weight=0;auto c=cfg();c.initial_step_fraction=10;auto r=MoreauProximalSolver(c,sc).solve(db,g);(void)r;Box core=db.coreBounds();for(auto& ce:db.cells())if(ce.isMovable())assert(ce.x>=core.lx-EPS&&ce.y>=core.ly-EPS&&ce.x+ce.width<=core.ux+EPS&&ce.y+ce.height<=core.uy+EPS);}
 {auto d1=two(),d2=two();BinGrid g1(d1,4,1,1),g2(d2,4,1,1);SubgradientConfig sc;sc.density_weight=0;auto c=cfg();auto r1=MoreauProximalSolver(c,sc).solve(d1,g1),r2=MoreauProximalSolver(c,sc).solve(d2,g2);near(r1.final_metrics.total_cost,r2.final_metrics.total_cost);near(r1.final_proximal_metrics.proximal_objective,r2.final_proximal_metrics.proximal_objective);assert(r1.history.size()==r2.history.size());for(size_t i=0;i<d1.cells().size();++i){near(d1.cells()[i].x,d2.cells()[i].x);near(d1.cells()[i].y,d2.cells()[i].y);}}
 {auto throws=[](MoreauProximalConfig c){bool th=false;try{SubgradientConfig sc;MoreauProximalSolver s(c,sc);}catch(const std::invalid_argument&){th=true;}assert(th);};auto c=cfg();c.mu=0;throws(c);c=cfg();c.mu=std::numeric_limits<double>::quiet_NaN();throws(c);c=cfg();c.mu=std::numeric_limits<double>::infinity();throws(c);c=cfg();c.max_inner_iterations=-1;throws(c);c=cfg();c.initial_step_fraction=0;throws(c);c=cfg();c.minimum_step_fraction=9;throws(c);c=cfg();c.backtrack_factor=1;throws(c);c=cfg();c.max_line_search_trials=0;throws(c);c=cfg();c.max_stall_iterations=0;throws(c);c=cfg();c.residual_rms_tolerance=-1;throws(c);}
 {auto db=two();auto cells=db.cells(); auto nets=db.nets(); auto rows=db.rows();BinGrid g(db,4,1,1);SubgradientConfig sc;sc.density_weight=0;(void)MoreauProximalSolver(cfg(),sc).solve(db,g);for(size_t i=0;i<db.cells().size();++i){near(db.cells()[i].width,cells[i].width);near(db.cells()[i].height,cells[i].height);assert(db.cells()[i].type==cells[i].type);assert(db.cells()[i].is_fixed==cells[i].is_fixed);assert(db.cells()[i].orientation==cells[i].orientation);assert(db.cells()[i].pin_ids==cells[i].pin_ids);}assert(db.nets().size()==nets.size()&&db.rows().size()==rows.size());BinGrid g2(db,4,1,1);near(g.totalMovableArea(),g2.totalMovableArea());near(g.totalOverflow(),g2.totalOverflow());assert(g.overflowBinCount()==g2.overflowBinCount());auto m1=ObjectiveEvaluator{}.evaluate(db,g,0),m2=ObjectiveEvaluator{}.evaluate(db,g2,0);near(m1.total_cost,m2.total_cost);}
}
