#include "clustering/DynamicClusterHypergraph.h"
#include <algorithm>
#include <cmath>
#include <stdexcept>
#include <unordered_set>
DynamicClusterHypergraph::DynamicClusterHypergraph(const PlacementDB& db){clusters_.reserve(db.cells().size()); for(const auto& c:db.cells()){ClusterNode n; n.id=c.id; n.movable=c.isMovable(); n.area=c.width*c.height; n.original_cell_ids={c.id}; clusters_.push_back(n);} for(const auto& net:db.nets()){ClusterNet cn; cn.id=net.id; for(int p:net.pin_ids) cn.cluster_ids.push_back(db.pin(p).cell_id); nets_.push_back(cn);} normalizeAll();}
DynamicClusterHypergraph::DynamicClusterHypergraph(std::vector<ClusterNode> c,std::vector<ClusterNet> n):clusters_(std::move(c)),nets_(std::move(n)){normalizeAll();}
void DynamicClusterHypergraph::normalizeAll(){for(size_t i=0;i<clusters_.size();++i)clusters_[i].id=(int)i; for(size_t i=0;i<nets_.size();++i){auto& v=nets_[i].cluster_ids; nets_[i].id=(int)i; std::sort(v.begin(),v.end()); v.erase(std::unique(v.begin(),v.end()),v.end()); v.erase(std::remove_if(v.begin(),v.end(),[&](int c){return c<0||c>=(int)clusters_.size()||!clusters_[c].active;}),v.end()); nets_[i].active=v.size()>=2;} rebuildIncidentNets();}
void DynamicClusterHypergraph::rebuildIncidentNets(){for(auto& c:clusters_) c.incident_net_ids.clear(); for(const auto& n:nets_) if(n.active) for(int c:n.cluster_ids) clusters_[c].incident_net_ids.push_back(n.id); for(auto& c:clusters_){std::sort(c.incident_net_ids.begin(),c.incident_net_ids.end()); c.incident_net_ids.erase(std::unique(c.incident_net_ids.begin(),c.incident_net_ids.end()),c.incident_net_ids.end());}}
int DynamicClusterHypergraph::activeMovableClusterCount()const{int n=0; for(auto& c:clusters_) if(c.active&&c.movable)++n; return n;} int DynamicClusterHypergraph::activeNetCount()const{int n=0; for(auto& e:nets_) if(e.active)++n; return n;} int DynamicClusterHypergraph::activePinCount()const{int n=0; for(auto&e:nets_) if(e.active)n+=(int)e.cluster_ids.size(); return n;} double DynamicClusterHypergraph::activeMovableArea()const{double a=0; for(auto&c:clusters_) if(c.active&&c.movable)a+=c.area; return a;}
std::vector<int> DynamicClusterHypergraph::activeNeighbors(int id)const{std::unordered_set<int>s; for(int ni:clusters_.at(id).incident_net_ids){auto& net=nets_[ni]; if(!net.active)continue; for(int c:net.cluster_ids) if(c!=id&&clusters_[c].active) s.insert(c);} std::vector<int> v(s.begin(),s.end()); std::sort(v.begin(),v.end()); return v;}
double DynamicClusterHypergraph::internalDegree(int j,int k)const{if(j==k)return 0; double d=0; for(int ni:clusters_.at(j).incident_net_ids){auto& n=nets_[ni]; if(!n.active)continue; if(std::binary_search(n.cluster_ids.begin(),n.cluster_ids.end(),k)){int p=(int)n.cluster_ids.size(); if(p>=2)d+=1.0/(p-1);}} return d;}
double DynamicClusterHypergraph::externalDegree(int j)const{std::unordered_map<int,double> m; for(int ni:clusters_.at(j).incident_net_ids){auto& n=nets_[ni]; if(!n.active)continue; int p=(int)n.cluster_ids.size(); if(p<2)continue; double w=1.0/(p-1); for(int c:n.cluster_ids) if(c!=j&&clusters_[c].active) m[c]+=w;} double e=0; for(auto&kv:m)e+=kv.second; return e;}
std::optional<BestNeighbor> DynamicClusterHypergraph::findMaximumScoreNeighbor(int id)const{if(!clusters_.at(id).active||!clusters_[id].movable)return std::nullopt; BestNeighbor best; bool found=false; double ej=externalDegree(id); for(int k:activeNeighbors(id)){if(!clusters_[k].movable)continue; double d=internalDegree(id,k); if(d<=0)continue; double s=scorer_.evaluate({clusters_[id].area,clusters_[k].area,ej,externalDegree(k),d,id,k}); if(s>best.score||(!found)|| (s==best.score&&k<best.cluster)){best={k,s,d}; found=true;}} if(!found||best.score<=0)return std::nullopt; return best;}
int DynamicClusterHypergraph::mergeClusters(int j,int k){if(j==k||!clusters_.at(j).active||!clusters_.at(k).active||!clusters_[j].movable||!clusters_[k].movable) throw std::invalid_argument("mergeClusters: invalid movable pair"); int nid=(int)clusters_.size(); ClusterNode nn; nn.id=nid; nn.area=clusters_[j].area+clusters_[k].area; nn.movable=true; nn.original_cell_ids=clusters_[j].original_cell_ids; nn.original_cell_ids.insert(nn.original_cell_ids.end(),clusters_[k].original_cell_ids.begin(),clusters_[k].original_cell_ids.end()); std::sort(nn.original_cell_ids.begin(),nn.original_cell_ids.end()); nn.original_cell_ids.erase(std::unique(nn.original_cell_ids.begin(),nn.original_cell_ids.end()),nn.original_cell_ids.end()); clusters_[j].active=clusters_[k].active=false; clusters_[j].version++; clusters_[k].version++; clusters_.push_back(nn); std::unordered_set<int> aff(clusters_[j].incident_net_ids.begin(),clusters_[j].incident_net_ids.end()); aff.insert(clusters_[k].incident_net_ids.begin(),clusters_[k].incident_net_ids.end()); for(int ni:aff){auto& v=nets_[ni].cluster_ids; for(int& c:v) if(c==j||c==k)c=nid; std::sort(v.begin(),v.end()); v.erase(std::unique(v.begin(),v.end()),v.end()); v.erase(std::remove_if(v.begin(),v.end(),[&](int c){return !clusters_[c].active;}),v.end()); nets_[ni].active=v.size()>=2;} rebuildIncidentNets(); for(int nb:activeNeighbors(nid)){clusters_[nb].valid=false; clusters_[nb].version++;} return nid;}
bool DynamicClusterHypergraph::checkNoDuplicateActiveNetIncidence()const{for(auto&n:nets_) if(n.active){if(n.cluster_ids.size()<2)return false; for(size_t i=1;i<n.cluster_ids.size();++i) if(n.cluster_ids[i-1]>=n.cluster_ids[i])return false; for(int c:n.cluster_ids) if(!clusters_[c].active)return false;} return true;}
