#include "density/ExactBinGrid.h"
#include "db/Cell.h"
#include "db/PlacementDB.h"
#include <algorithm>
#include <cmath>
#include <limits>
#include <stdexcept>
namespace { constexpr double kTol=1e-9; void finiteNonneg(double v,const char* n){ if(!std::isfinite(v)||v < -kTol) throw std::runtime_error(std::string("ExactBinGrid: invalid ")+n); } double overlap(const Box&a,const Box&b){ double ox=std::min(a.ux,b.ux)-std::max(a.lx,b.lx); double oy=std::min(a.uy,b.uy)-std::max(a.ly,b.ly); return (ox>0.0&&oy>0.0)?ox*oy:0.0;} bool near(double a,double b){return std::abs(a-b)<=kTol*std::max({1.0,std::abs(a),std::abs(b)});} }
ExactBinGrid::ExactBinGrid(const PlacementDB& db,int bx,int by,double td):bins_x_(bx),bins_y_(by),target_density_(td){ if(bx<=0||by<=0) throw std::invalid_argument("ExactBinGrid: bins_x and bins_y must be positive"); if(!std::isfinite(td)||td<=0.0||td>1.0) throw std::invalid_argument("ExactBinGrid: target_density must satisfy 0 < value <= 1"); rebuild(db); }
const Bin& ExactBinGrid::bin(int id) const { if(id<0||id>=static_cast<int>(bins_.size())) throw std::out_of_range("ExactBinGrid::bin: invalid bin id"); return bins_[id]; }
void ExactBinGrid::rebuild(const PlacementDB& db){ core_=db.coreBounds(); if(!core_.valid()||!std::isfinite(core_.area())) throw std::runtime_error("ExactBinGrid: invalid core bounds"); bin_width_=core_.width()/bins_x_; bin_height_=core_.height()/bins_y_; if(!(bin_width_>0.0)||!(bin_height_>0.0)||!std::isfinite(bin_width_)||!std::isfinite(bin_height_)) throw std::runtime_error("ExactBinGrid: invalid bin dimensions"); bins_.clear(); bins_.reserve(static_cast<size_t>(bins_x_*bins_y_)); for(int iy=0;iy<bins_y_;++iy){ for(int ix=0;ix<bins_x_;++ix){ Bin b; b.id=iy*bins_x_+ix; b.ix=ix; b.iy=iy; b.bounds.lx=core_.lx+ix*bin_width_; b.bounds.ly=core_.ly+iy*bin_height_; b.bounds.ux=(ix==bins_x_-1)?core_.ux:core_.lx+(ix+1)*bin_width_; b.bounds.uy=(iy==bins_y_-1)?core_.uy:core_.ly+(iy+1)*bin_height_; const double area=b.bounds.area(); if(!(area>0.0)||!std::isfinite(area)) throw std::runtime_error("ExactBinGrid: bin area must be positive"); b.target_capacity=target_density_*area; bins_.push_back(std::move(b)); }} total_cell_area_=total_movable_area_=total_fixed_area_=0.0; double expected_total=0, expected_movable=0, expected_fixed=0; for(const Cell& c: db.cells()){ if(!std::isfinite(c.x)||!std::isfinite(c.y)||!std::isfinite(c.width)||!std::isfinite(c.height)||c.width<0.0||c.height<0.0) throw std::runtime_error("ExactBinGrid: invalid cell geometry for "+c.name); Box cb{c.x,c.y,c.x+c.width,c.y+c.height}; Box clipped{std::max(cb.lx,core_.lx),std::max(cb.ly,core_.ly),std::min(cb.ux,core_.ux),std::min(cb.uy,core_.uy)}; if(!clipped.valid()) continue; const double clipped_area=clipped.area(); expected_total+=clipped_area; if(c.isMovable()) expected_movable+=clipped_area; else expected_fixed+=clipped_area; int ix0=std::max(0, static_cast<int>(std::floor((clipped.lx-core_.lx)/bin_width_))); int iy0=std::max(0, static_cast<int>(std::floor((clipped.ly-core_.ly)/bin_height_))); int ix1=std::min(bins_x_-1, static_cast<int>(std::ceil((clipped.ux-core_.lx)/bin_width_))-1); int iy1=std::min(bins_y_-1, static_cast<int>(std::ceil((clipped.uy-core_.ly)/bin_height_))-1); for(int iy=iy0;iy<=iy1;++iy) for(int ix=ix0;ix<=ix1;++ix){ Bin& b=bins_[iy*bins_x_+ix]; double a=overlap(cb,b.bounds); if(a>0.0){ finiteNonneg(a,"overlap area"); b.total_area+=a; if(c.isMovable()) b.movable_area+=a; else b.fixed_area+=a; b.overlapping_cell_ids.push_back(c.id); } } }
 for(Bin& b: bins_){ if(!near(b.total_area,b.movable_area+b.fixed_area)) throw std::runtime_error("ExactBinGrid: bin area split mismatch"); b.overflow=std::max(0.0,b.total_area-b.target_capacity); b.density_ratio=b.total_area/b.bounds.area(); total_cell_area_+=b.total_area; total_movable_area_+=b.movable_area; total_fixed_area_+=b.fixed_area; }
 if(!near(total_cell_area_,expected_total)||!near(total_movable_area_,expected_movable)||!near(total_fixed_area_,expected_fixed)) throw std::runtime_error("ExactBinGrid: clipped area conservation mismatch"); }
